# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.initrd.luks.devices."luks-81a767c2-7526-4dc9-a77f-e699382c8c64".keyFile = "/crypto_keyfile.bin";
  
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2cd02a66-656b-45a5-a96d-3cf50c1b26fa";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7b2ecade-bf64-4ae2-9911-05c5a300c07d";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/91BD-3BB1";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/2a6fc2f4-8329-4788-8211-da9f0013e2e1";
      fsType = "ext4";
    };

  fileSystems."/mnt/work" =
    { device = "/dev/disk/by-uuid/fbb81204-4039-486f-935e-5b5ba007e292";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-81a767c2-7526-4dc9-a77f-e699382c8c64".device = "/dev/disk/by-uuid/81a767c2-7526-4dc9-a77f-e699382c8c64";

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
